#Rename to config.yaml
#and fill up with your data
bot:
  botName: 'BOT NAME'
  botToken: 'BOT_TOKEN'
  adminId: TELEGRAM_ID
metalvis:
  x-api-key: 'YOUR_API_KEY'
  wellcome_message: 'bot loaded'
  api_url: 'url = "https://APIAPI.ua/uk/api/'  